project:
  type: book

lang: pt

book:
  title: "Nome do Livro"
  subtitle: "Subtítulo"
  reader-mode: true

  page-footer:
    left: |
      Nota de rodapé a esquerda.
    right: |
      Este livro foi feito com <a href="https://quarto.org/">Quarto</a>.

  author:
    - "Alfredo Goldman"
    - "Lucas de Sousa Rosa"
  date: "last-modified"
  chapters:
    - index.qmd
    - aulas/aula1.qmd
    - aulas/aula2.qmd
    - aulas/aula3.qmd
    - aulas/aula4.qmd
    - aulas/aula5.qmd
    - aulas/aula6.qmd
    - aulas/aula7.qmd
#    - references.qmd

bibliography: references.bib

execute:
  cache: true
  daemon: true
  freeze: auto

format:
  html:
    theme: cosmo
    author-meta: "Alfredo Goldman e Lucas de Sousa Rosa"
  pdf:
    documentclass: scrreprt
ipynb-shell-interactivity: all



