project:
  type: book
  output-dir: .

lang: pt

book:
  title: "Introdução à Linguagem Julia"
  author:
    - "Alfredo Goldman"
    - "Lucas de Sousa Rosa"
  date: "last-modified"
  chapters:
    - index.qmd
    - aulas/01.qmd
    - aulas/02.qmd
    - aulas/03.qmd
    - aulas/04.qmd
    - aulas/05.qmd
    - aulas/06.qmd
    - aulas/07.qmd
    - aulas/08.qmd
    - aulas/09.qmd
    - aulas/10.qmd
    - aulas/11.qmd

execute:
  cache: true
  freeze: auto

format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true