project:
  type: book

lang: pt

book:
  title: "Uma Introdução à Computação com Julia"
  author:
    - "Alfredo Goldman"
    - "Lucas de Sousa Rosa"
  repo-url: https://github.com/firilisinof/livro-intro-comp-julia
  downloads: [pdf]
  date: "last-modified"
  chapters:
    - index.qmd
    - sobre-o-curso.qmd
    - chapters/01.qmd
    - chapters/02.qmd
    - chapters/03.qmd
    - chapters/04.qmd
    - chapters/05.qmd
    - chapters/06.qmd
    - chapters/07.qmd
    - chapters/08.qmd
    - chapters/09.qmd
    - chapters/10.qmd
    - chapters/11.qmd
    - chapters/12.qmd
    - chapters/13.qmd
    - chapters/14.qmd
    - chapters/15.qmd
    - chapters/16.qmd
    - chapters/17.qmd
    - agradecimentos.qmd

execute:
  cache: true
  freeze: auto
  daemon: 120

format:
  html:
    theme: cosmo
  pdf:
    toc: true
    number-sections: true
    colorlinks: true